server:
  port: 9856
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #数据库下划线自动转驼峰标示关闭
  mapper-locations: classpath:org/example/mapper/xml/*.xml
spring:
  security:
    filter:
      order: -100
    jwt:
      key: abcdefg
      expire: 7
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://47.101.203.178:3306/instructor_assistant
    username: peco233_com
    password: 1797383887jyf
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username: tukumij@163.com
    password: DJLANCLVJRYTODAK
  rabbitmq:
    addresses: 47.101.203.178:5672
    username: admin
    password: 1797383887jyf
    virtual-host: /instructor_assistant
  minio:
    endpoint: 'http://47.101.203.178:9000'
    username: 'minio'
    password: 'password'
  weather:
    key: cc48d7d106ee43b798961bbbfc07c236
  data:
    redis:
      host: 47.101.203.178
      port: 6379
      database: 0
      password: 1797383887jyf
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      database: 0